#!/dis/sh
fn connexion{
	ndb/cs
	cat /net/tcp/clone>/dev/null
	<>[3]/net/tcp/0/ctl{
		echo 'connect 127.0.0.1!9000 2000'>[1=3]
		echo 'connexion effectué'
		bind -a '#a' /tls
		<>[4]/tls/clone{
#			cat <[0=4]
		<>[6]/net/tcp/0/data{
			<>[3]/tls/0/ctl{
				echo 'client'>[1=3]
				echo 'fd 6'>[1=3]
				<>[7]/tls/0/data{
				echo 'hello server' >[1=7]
				#ls -l
				#netstat
				cat <[7=0]
				}
			}
		}
	}
	}
}

connexion
