#!/dis/sh
fn connexion{
	ndb/cs
	cat /net/tcp/clone>/dev/null
	<>[3]/net/tcp/0/ctl{
		echo 'connect 127.0.0.1!9000 2000'>[1=3]
		echo 'connexion effectué'
		bind -a '#D' /ssl
		#bind /ssl /ssl
		cat /ssl/clone>/dev/null
		<>[6]/net/tcp/0/data{
		#	echo 'client'>[1=6]
			<>[3]/ssl/0/ctl{
				#netstat
				echo 'fd 6'>[1=3]
			<>[4]/ssl/0/secretin{
				echo 'helloJAJAJA1289'>[1=4]
				<>[5]/ssl/0/secretout{
				echo 'helloJAJAJA1289'>[1=5]
				echo 'alg rc4'>[1=3]
				<>[7]/ssl/0/data{
				echo 'hello server' >[1=7]
				cat <[0=7]
				}
			}
			}

			}
		}
	}
}

connexion
