#!dis/sh
fn ouverture_port{
	ndb/cs
	echo hello
	cat /net/tcp/clone
	<>[3]/net/tcp/0/ctl{
	echo 'announce 127.0.0.1!9000'>[1=3]
		<>[4]/net/tcp/0/listen{
			echo 'got connection from' `{cat net/tcp/1/remote} 
			bind -a '#a' /tls
			<>[5]/tls/clone{
				#cat <[0=5]
			<>[4]/net/tcp/1/data{
			<>[3]/tls/0/ctl{
				echo 'server' >[1=3]
				echo 'fd 4' >[1=3]
				<>[5]/tls/0/data{
				echo 'hello client' >[1=5]
				cat <[0=5]
				}
			}
			}
			}
		}
	}
}
ouverture_port
