#!dis/sh
fn ouverture_port{
	ndb/cs
	echo hello
	cat /net/tcp/clone
	<>[3]/net/tcp/0/ctl{
	echo 'announce 127.0.0.1!9000'>[1=3]
		<>[4]/net/tcp/0/listen{
			echo 'got connection from' `{cat net/tcp/1/remote}
			bind -a '#D' /ssl
			bind /ssl /ssl
			cat /ssl/clone
#			
			<>[4]/net/tcp/1/data{
		#	id = "{ cat <[4=0]}
			#echo 'test'>[1=4]
			<>[3]/ssl/0/ctl{
				#netstat							#echo id: $id
				echo 'fd 4' >[1=3]
			<>[6]/ssl/0/secretin{
				echo 'helloJAJAJA1289'>[1=6]
			<>[5]/ssl/0/secretout{
				echo 'helloJAJAJA1289'>[1=5]
				echo  'alg rc4'>[1=3]
				echo 'hello client'>/ssl/0/data
				cat /ssl/0/data
			}
			}
			}
			#netstat
			#<>[3]/net/tcp/1/data{echo 'hello there'>[1=3]}
			#echo 'hangup' >[1=4]
			}
		}
	}
}
ouverture_port
